// battleboat
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_SHADOWBOARD_SUCCESS  = 'GET_SHADOWBOARD_SUCCESS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE';