// battleboat
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const FIRE_SUCCESS = 'FIRE_SUCCESS';
export const GET_PLAYERLIST_SUCCESS = 'GET_PLAYERLIST_SUCCESS';
export const GET_GRID_SUCCESS = 'GET_GRID_SUCCESS';
export const GET_SHIPS_SUCCESS = 'GET_SHIPS_SUCCESS';
export const GET_TEAMNAME_SUCCESS = 'GET_TEAMNAME_SUCCESS';
export const SET_TEAMNAME_SUCCESS = 'SET_TEAMNAME_SUCCESS';
export const GET_GAMENAME_SUCCESS = 'GET_GAMENAME_SUCCESS';
export const SET_GAMENAME_SUCCESS = 'SET_GAMENAME_SUCCESS';
export const GET_GAMEDESC_SUCCESS = 'GET_GAMEDESC_SUCCESS';
export const SET_GAMEDESC_SUCCESS = 'SET_GAMEDESC_SUCCESS';
export const GET_SHADOWBOARD_SUCCESS  = 'GET_SHADOWBOARD_SUCCESS';
export const SET_SHADOWBOARD_SUCCESS  = 'SET_SHADOWBOARD_SUCCESS';

export const SHOTS_CHANGED = 'SHOTS_CHANGED';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE';